### ISSUE TITLE
How we can manage user role?

### ISSUE THREAD

**Issue by skanel** [gladius/firebase-spring-boot-rest-api-authentication#1]
Can you please help to guide me how to implement the user roles?

**Comment by davidecampello** [comment]
Hello, have you found a solution? Thank you

**Comment by gladius** [comment]
@davidecampello yes I have, I will push an update with role management by tomorrow

**Comment by gladius** [comment]
role management is now available.

**Comment by davidecampello** [comment]
Hi @gladius! Thank you very much for this!
