### ISSUE TITLE
Is this suitable for android or flutter as a front end?

### ISSUE THREAD

**Issue by mod-ali** [gladius/firebase-spring-boot-rest-api-authentication#15]
Is this suitable for android or flutter as a front end?

**Comment by gladius** [comment]
@Emarcode yes this starter can work as a middleware for flutter or android. I have used it with several flutter projects.

If your project is fully mobile based, disable cookies using  `enable-strict-server-session=false`  and rely on tokens based auth only. 

I will try to add a flutter demo project sometime soon.
